spring:
  datasource:
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Kdoornega0128!}
    driver-class-name: ${JDBC_DRIVER_SOURCE:com.mysql.cj.jdbc.Driver}
    url: ${DB_URL:jdbc:mysql://localhost:3306/store?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect


server:
  port: ${SERVER_PORT:8080}
logging:
  level:
    com.example.user: trace
